# http://docs.docker.jp/compose/rails.html
# https://hub.docker.com/_/mysql/
version: '3.7'

networks:
  default:
    name: docker-lan

services:

  localstack:
    image: localstack/localstack
    environment:
      DEFAULT_REGION: ap-notrheast-1
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      DATA_DIR: /tmp/localstack/data
      SERVICES: serverless
    volumes:
      - ./localstack:/tmp/localstack

  dynamodb-admin:
    build:
      context: .
      dockerfile: ./Dockerfiles/dynamodb-admin.Dockerfile
    command: dynamodb-admin
    ports:
      - '5001:8001'
    depends_on:
      - localstack
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: ap-notrheast-1

  api:
    build:
      context: .
      dockerfile: ./Dockerfiles/ruby.Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    # command: bash -c 'bundle exec jets server --host 0.0.0.0 --port 3000'
    environment:
      LANG: C.UTF-8
      EDITOR: vim
      BUNDLE_APP_CONFIG: /app/.bundle
    env_file:
      - ./Envfiles/api.env
    # depends_on:
      # - postgres
      # - mysql
    volumes:
      - ./api:/app:cached
      - ./api/bundle:/app/bundle
    tty: true

  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/node.Dockerfile
    container_name: web
    command: bash -c 'yarn start --host 0.0.0.0'
    ports:
      - '8000:3000'
    env_file:
      - ./Envfiles/web.env
    volumes:
      - ./web:/app:cached
      - ./web/node_modules:/app/node_modules
    tty: true
